:concurrency: 5
:queues:
    - default
:scheduler:
    send_signup_email:
        cron: "*/2 * * * *"
        class: "SendSignupEmailJob"
    send_order_confirmation_email:
        cron: "*/2 * * * *"
        class: "SendOrderConfirmationEmailJob"
